### ISSUE TITLE
1M sentences data

### ISSUE THREAD

**Issue by wenyudu** [harvardnlp/urnng#2]
Hi, 

Thanks for releasing the code!

Could you please also release the 1M sentences data? Because I hope to replicate the results but I noticed it was just randomly sampled from one billion word corpus. 

Many Thanks.

**Comment by yoonkim** [comment]
Hi sorry for the late response. Since we didn't use the standard splits for 1b we did not release the dataset. But I am happy to send over the sampled dataset if you would like. (What is your email address?)

**Comment by wenyudu** [comment]
> Hi sorry for the late response. Since we didn't use the standard splits for 1b we did not release the dataset. But I am happy to send over the sampled dataset if you would like. (What is your email address?)

Thanks for your reply. I would like to receive the dataset. My email address is wenyudu@yahoo.com

**Comment by yoonkim** [comment]
Great! Just sent.

**Comment by eece-23** [comment]
HI!  @yoonkim 
I also would like to receive the dataset. Could you send me a dataset? My email address is farsoftwind@gmail.com

**Comment by yoonkim** [comment]
Great! Just sent

**Comment by sychairazulfa** [comment]
Hi.

Do you still have the data?
Is the data in bahasa indonesia?
