### ISSUE TITLE
how can I start parsing training from scratch with plain text?

### ISSUE THREAD

**Issue by eece-23** [harvardnlp/urnng#4]
The train set for parsing need Penn Treebank .
how can I start my training from scratch with plain text?

**Comment by yoonkim** [comment]
Hi sorry for the delayed response! Right now the codebase only supports treebank-style inputs. You will need to slightly modify the `preprocess.py` for it to work on plain text. Or you fake a treebank by making your training set look like `data/train.txt` with (for example) right branching trees.
