### ISSUE TITLE
What is ptb-test.txt?

### ISSUE THREAD

**Issue by redevaaa** [harvardnlp/urnng#5]

**Comment by redevaaa** [comment]
Thank you for your awesome code and paper.

I am trying to evaluate the unlabeled constituency parsing. But are confused about the ptb-test.txt in the command line like below. What is this file? How could I get it??

`python parse.py --model_file urnng.pt --data_file data/ptb-test.txt --out_file pred-parse.txt 
--gold_out_file gold-parse.txt --gpu 0`

**Comment by yoonkim** [comment]
Oh sorry for the confusion. It should be the test set from PTB. The format should be the same as `data/test.txt`

**Comment by redevaaa** [comment]
Thanks for your timely response. 
But the format of data/test.txt is labeled and parsed ones. When we evaluate the unlabeled constituency parsing F1 score,  isn't the input test data the plain text format?

**Comment by yoonkim** [comment]
Right, so the input to parse is also in the treebank format (with the gold trees) in order to calculate the F1 score.
