### ISSUE TITLE
A question about implementation details

### ISSUE THREAD

**Issue by speedcell4** [harvardnlp/urnng#7]
https://github.com/harvardnlp/urnng/blob/28917b369c3122012490657b1eb68bde1821251d/models.py#L71

you concatenate `prev_h ` with hidden state from the last layer, but all of your `prev_h` are just zero tensors, right? so what's the point to do so?

**Comment by yoonkim** [comment]
Hi! They are zero tensors when the stack is empty, but should be the previous stack LSTM representation when the stack is not empty.
