### ISSUE TITLE
A subtle bug on preprocess.py when loading external vocab

### ISSUE THREAD

**Issue by galsang** [harvardnlp/urnng#9]
Hello YK, 

Thanks always for releasing this great resource useful for follow-up studies.

I just wanna report a subtle bug in the **processing.py,** which I came across during trying to train urnng with the induced trees from compound-pcfg following your paper.

https://github.com/harvardnlp/urnng/blob/28917b369c3122012490657b1eb68bde1821251d/preprocess.py#L60-L67

I think self.idx2word should be re-initialized in the above code snippet, for example, by injecting self.idx2word = {} between line 64 and 65.
Because some of the original word-idx pairs which are not needed anymore would still remain even after executing the function if the original vocab is not a subset of a new vocab.

This bug actually leads to an error when running **parse.py** with an urnng instance that is trained with the induced trees from compound-pcfg.

However, it looks just minor and doesn't seem to have an impact on model training.
Just please considering injecting the simple one-line code if you have free time to do so.
Thanks!

**Comment by yoonkim** [comment]
Thanks very much for identifying this! I've committed a fix.
